if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


## Plugins
eval $(thefuck --yeah --alias --enable-experimental-instant-mode)
eval "$(fasd --init auto)"

## Aliases
alias nv="nvim"
alias vs="code"